### ISSUE TITLE
Cut libndt v0.27.0 release ASAP

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/libndt#143]
Long time has passed since last stable release. Let's cut a v0.27.0 release before doing more refactoring and improving unit tests. I am aiming to use bd30e809e92e30b0c3a3ffd2f153f69a2b9fc214 as target for the tag.

@robertodauria does that sound good? Would you rather tag the current master, or wait for #142 to be merged so we have a more understandable tree? Please, let me know!

**Comment by robertodauria** [comment]
Good idea. https://github.com/measurement-kit/libndt/commit/bd30e809e92e30b0c3a3ffd2f153f69a2b9fc214 seems like the right commit to tag as well - just before the refactoring started.

**Comment by bassosimone** [comment]
Done!
