### ISSUE TITLE
Add an informative summary message at the end of each test

### ISSUE THREAD

**Issue by robertodauria** [measurement-kit/libndt#147]
Right now ndt5 provides a very basic human-readable summary ([currently broken](https://github.com/measurement-kit/libndt/issues/146)) and ndt7 does not provide any. It would be useful to have a summary containing - at least:
- C2S rate
- S2C rate
- Average RTT
- Retransmission rate
- Jitter (?)

**Comment by critzo** [comment]
Summarizing a plan based on chat with @robertodauria  :
* `./libndt-client` : runs a test, prints a summary at the end
* `./libndt-client -verbose` : same as above + (periodic) JSON with TCPInfo and BBR data
* `./libndt-client -batch` : all of the above, including periodic messages while the test is running and the summary, in JSON format 
* `./libndt-client -summary` : single summary JSON message only
